#ifndef SL_COMPONENT_CATALOG_H
#define SL_COMPONENT_CATALOG_H

// APIs present in project
#define SL_CATALOG_IOSTREAM_PRESENT
#define SL_CATALOG_RETARGET_STDIO_PRESENT
#define SL_CATALOG_SL_CORE_PRESENT
#define SL_CATALOG_SL_MAIN_PRESENT

#endif // SL_COMPONENT_CATALOG_H
